name: Python CI with Ruff Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Create virtual environment with uv
        run: uv venv
      - name: Install all dependencies via uv
        run: |
          source .venv/bin/activate
          uv pip install .
          uv pip install . --group dev
      
      - name: "Run Tests"
        run: |
          source .venv/bin/activate
          pytest --cov=code_wise --cov-report=term-missing

  lint:
    runs-on: ubuntu-latest
    needs: test  # This ensures the lint job runs after the test job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Create virtual environment with uv
        run: uv venv
      - name: Install Ruff via uv
        run: |
          source .venv/bin/activate
          uv pip install ruff

      - name: Run Ruff Linter
        run: |
          source .venv/bin/activate  
          ruff check . --fix